CREATE DATABASE test9


CREATE TABLE Countries(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CountryName NVARCHAR(50) NOT NULL,
); 

CREATE TABLE Gender(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Gender1 NVARCHAR(50) NOT NULL,
); 

CREATE TABLE Roles(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	RoleName NVARCHAR(50) NOT NULL,
); 
use test9; 
CREATE TABLE Users(
	Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	IdRole INT NOT NULL,
	IdCountry INT NOT NULL,
	IdGender INT NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	FOREIGN KEY(IdRole) REFERENCES Roles(Id),
	FOREIGN KEY(IdCountry) REFERENCES Countries(Id),
	FOREIGN KEY(IdGender) REFERENCES Gender(Id),
); 